FROM debian:12

ARG KALDI_MKL

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        bzip2 \
        unzip \
        xz-utils \
        g++ \
        make \
        cmake \
        git \
        python3 \
        python3-dev \
        python3-websockets \
        python3-setuptools \
        python3-pip \
        python3-wheel \
        python3-cffi \
        zlib1g-dev \
        automake \
        autoconf \
        libtool \
        pkg-config \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi

RUN cd /opt/kaldi/tools && \
    sed -i 's:status=0:exit 0:g' extras/check_dependencies.sh && \
    sed -i 's:--enable-ngram-fsts:--enable-ngram-fsts --disable-bin:g' Makefile && \
    make -j $(nproc) openfst CXX=g++-aarch64-linux-gnu

RUN apt-get install -y libopenblas-dev

RUN cd /opt/kaldi/src && \
    ./configure --mathlib=OPENBLAS --shared && \
    sed -i 's:-msse -msse2::g' kaldi.mk && \
    sed -i 's: -O1 : -O3 :g' kaldi.mk && \
    make -j $(nproc) online2 lm rnnlm

RUN git clone https://github.com/alphacep/vosk-api /opt/vosk-api && \
    cd /opt/vosk-api/src && \
    KALDI_MKL=$KALDI_MKL KALDI_ROOT=/opt/kaldi make -j $(nproc) && \
    cd /opt/vosk-api/python && \
    python3 ./setup.py install

RUN git clone https://github.com/alphacep/vosk-server /opt/vosk-server

RUN rm -rf /opt/vosk-api/src/*.o && \
    rm -rf /opt/kaldi && \
    rm -rf /root/.cache && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 2700

CMD ["python3", "/opt/vosk-server/websocket/asr_server.py", "/opt/vosk-model-en/model"]
